#!/bin/bash

#SBATCH --job-name=NN-DP-GD-crossval-ns
#SBATCH --output=logs/%A-%a_NN-DP-GD-crossval-ns

#SBATCH --ntasks=1
#SBATCH --time=8:00:00
#SBATCH --mem=48G

#SBATCH --mail-user=sbombari@ist.ac.at
#SBATCH --mail-type=END

#SBATCH --no-requeue

#SBATCH --partition=gpu
#SBATCH --gres=gpu:1

#Do not export the local environment to the compute nodes
#SBATCH --export=NONE
unset SLURM_EXPORT_ENV

module load jax-cuda/0.4.20

widths=(1000)
lrs=(0.1)
ns=(5 10 50 100 500 1000 5000 10000 50000)

for n in "${ns[@]}"; do
    for lr in "${lrs[@]}"; do
        for width in "${widths[@]}"; do
            srun python3 ./main_NN_JAX.py --k ${SLURM_ARRAY_TASK_ID} --width $width --lr $lr --n $n > outputs/NN-DP-GD_${SLURM_ARRAY_TASK_ID}_width_${width}.txt
        done
    done
done
