#!/bin/bash
#
#----------------------------------
# single GPU + single CPU example
#----------------------------------
#
#SBATCH --job-name=RF-original-12_09
#SBATCH --output=logs/%A-%a_RF-original-12_09

#number of CPUs to be used
#SBATCH --ntasks=1
#
#Define the number of hours the job should run.
#Maximum runtime is limited to 10 days, ie. 240 hours
#SBATCH --time=4:00:00
#
#Define the amount of system RAM used by your job in GigaBytes
#SBATCH --mem=64G
#

## SBATCH --reservation=mondegrp_61

#Send emails when a job starts, it is finished or it exits
#SBATCH --mail-user=sbombari@ist.ac.at
#SBATCH --mail-type=END
#
#Pick whether you prefer requeue or not. If you use the --requeue
#option, the requeued job script will start from the beginning,
#potentially overwriting your previous progress, so be careful.
#For some people the --requeue option might be desired if their
#application will continue from the last state.
#Do not requeue the job in the case it fails.
#SBATCH --no-requeue

#
#for single-CPU jobs make sure that they use a single thread
export OMP_NUM_THREADS=1

#Do not export the local environment to the compute nodes
#SBATCH --export=NONE
unset SLURM_EXPORT_ENV

#
#
#load an CUDA software module
module load jax-cuda/0.4.20

#
#run your CUDA binary through SLURM's srun

srun python3 main_less_time.py --k ${SLURM_ARRAY_TASK_ID} --dataset 'synthetic' > outputs/RF_original_${SLURM_ARRAY_TASK_ID}.txt

